// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface MiruTimerState {
  context: {
    billable: boolean;
    notes: string;
    projectId: string;
    projectName: string;
    taskId: string;
    taskName: string;
  };
  elapsedMs: number;
  elapsedSeconds: number;
  formatted: string;
  idle: {
    durationMs: number;
    prompted: boolean;
  } | null;
  idleThresholdSeconds: number;
  running: boolean;
  timers: Array<{
    context: MiruTimerState["context"];
    elapsedMs: number;
    elapsedSeconds: number;
    formatted: string;
    id: string;
    running: boolean;
    updatedAt: string;
  }>;
}

interface MiruSessionState {
  baseUrl: string;
  company: Record<string, unknown> | null;
  companyRole: string;
  currentWorkspaceId: number | string | null;
  lastSyncAt: string;
  signedIn: boolean;
  syncError: string;
  syncStatus: "error" | "local" | "offline" | "synced" | "syncing";
  user: Record<string, unknown> | null;
  workspaces: Array<{ id: number | string; name: string; logo?: string }>;
}

interface Window {
  miruApi: {
    deleteTimerEntry: (entryId: number | string) => Promise<unknown>;
    getTimeTracking: (payload?: {
      from?: string;
      to?: string;
      userId?: number | string;
    }) => Promise<MiruTimeTrackingPayload>;
    getSession: () => Promise<MiruSessionState>;
    googleLogin: (baseUrl?: string) => Promise<MiruSessionState>;
    login: (payload: {
      baseUrl?: string;
      email: string;
      password: string;
    }) => Promise<MiruSessionState>;
    logout: () => Promise<MiruSessionState>;
    saveTimerEntry: (payload: {
      duration?: number;
      note?: string;
      projectId?: number | string;
      userId?: number | string;
      workDate?: string;
    }) => Promise<unknown>;
    updateTimerEntry: (payload: {
      duration?: number;
      entryId?: number | string;
      note?: string;
      projectId?: number | string;
      workDate?: string;
    }) => Promise<unknown>;
    signup: (payload: {
      baseUrl?: string;
      email: string;
      firstName?: string;
      lastName?: string;
      password: string;
    }) => Promise<MiruSessionState>;
    switchWorkspace: (
      workspaceId: number | string
    ) => Promise<MiruSessionState>;
    syncCurrentTimer: (
      action?: "pull" | "push"
    ) => Promise<{ session: MiruSessionState; timer: MiruTimerState }>;
  };
  miruTimer: {
    applyIdleAction: (
      action: "remove-continue" | "remove-start-new" | "ignore-continue"
    ) => Promise<MiruTimerState>;
    forceIdleForTesting?: (durationMs: number) => Promise<MiruTimerState>;
    getState: () => Promise<MiruTimerState>;
    onStateChange: (callback: (state: MiruTimerState) => void) => () => void;
    pause: () => Promise<MiruTimerState>;
    reset: () => Promise<MiruTimerState>;
    deleteSlot: (timerId: string) => Promise<MiruTimerState>;
    resumeSlot: (timerId: string) => Promise<MiruTimerState>;
    setContext: (context: {
      billable: boolean;
      notes: string;
      projectId: string;
      projectName: string;
      taskId: string;
      taskName: string;
    }) => Promise<MiruTimerState>;
    setIdleThreshold: (seconds: number) => Promise<MiruTimerState>;
    setSummary: (summary: {
      entryCount: number;
      selectedDateLabel: string;
      selectedDateMinutes: number;
      syncStatus: MiruSessionState["syncStatus"];
      todayMinutes: number;
      userLabel: string;
      weekMinutes: number;
      workspaceName: string;
    }) => Promise<MiruTimerState>;
    start: () => Promise<MiruTimerState>;
    startNew: () => Promise<MiruTimerState>;
    toggle: () => Promise<MiruTimerState>;
  };
  nativeDialog: {
    closeWindow: () => Promise<void>;
    confirmDeleteTimeEntry: () => Promise<boolean>;
    minimizeWindow: () => Promise<void>;
    quitApp: () => Promise<void>;
  };
}

interface MiruTimeTrackingPayload {
  clients: Array<{ id: number | string; name: string }>;
  entries: Record<
    string,
    Array<{
      bill_status?: string;
      client?: string;
      duration: number;
      id: number | string;
      note?: string;
      project?: string;
      project_id?: number | string;
      source?: string;
      type?: string;
      work_date?: string;
    }>
  >;
  projects: Record<
    string,
    Array<{
      billable?: boolean;
      client_id: number | string;
      description?: string;
      id: number | string;
      name: string;
    }>
  >;
}
