name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - name: Install and build
        run: mise exec -- bun install --frozen-lockfile

      - name: Publish Release
        env:
          APPLE_NOTARIZE_KEYCHAIN_PROFILE: ${{ secrets.APPLE_NOTARIZE_KEYCHAIN_PROFILE }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mise exec -- bun run publish
